import 'package:clippy_flutter/clippy_flutter.dart';
import 'package:devide_manager/object/TypeOfDeviceObject.dart';
import 'package:devide_manager/provider/api_Type_Of_Device.dart';
import 'package:devide_manager/object/SupplierObject.dart';
import 'package:devide_manager/provider/api_Supplier.dart';
import 'package:devide_manager/object/RoomObject.dart';
import 'package:devide_manager/provider/api_Room.dart';
import 'package:devide_manager/object/FacultyOject.dart';
import 'package:devide_manager/provider/api_Faculties.dart';
import 'package:devide_manager/object/BrandObject.dart';
import 'package:devide_manager/provider/api_Brand.dart';
import 'package:flutter/material.dart';
import 'package:flutter_spinkit/flutter_spinkit.dart';
import 'package:http/http.dart' as http;
